### PR TITLE
LPS-72463

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
How do I see the report of the failed tests?

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@mbowerman I'm not sure how to see the results of this. I was hoping it would pass this time around. Do you know if other pulls are failing like this?

**Comment by mbowerman** [comment]
It looks like https://github.com/liferay/com-liferay-journal/pull/308 passed and was only sent two hours ago. It would be nice if I could see the results of the test so I could know what bug to fix. Who would know how to interpret the test results?

**Comment by jonathanmccann** [comment]
You could reach out to Eudaldo since he heads up WCM now. Other than him, I'm not sure. Perhaps the testing team?

**Comment by mbowerman** [comment]
I sent an email to @ealonso.

**Comment by jkappler** [comment]
@mbowerman, you can check in local by running gradlew pmdMain

**Comment by ealonso** [comment]
Hey @mbowerman and @jonathanmccann,

I've executed the "gradlew pmdMain" locally and the results is:

<html><head><title>PMD</title></head><body>
<center><h3>PMD report</h3></center><center><h3>Problems found</h3></center><table align="center" cellspacing="0" cellpadding="3"><tr>
<th>#</th><th>File</th><th>Line</th><th>Problem</th></tr>
<tr bgcolor="lightgrey"> 
<td align="center">1</td>
<td width="*%">/Users/eudaldo/proyectos/liferay/trunk/com-liferay-journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java</td>
<td align="center" width="5%">6554</td>
<td width="*"><a href="http://pmd.sourceforge.net/pmd-5.2.3/pmd-java/rules/java/unusedcode.html#UnusedLocalVariable">Avoid unused local variables such as 'ownerId'.</a></td>
</tr>
<tr> 
<td align="center">2</td>
<td width="*%">/Users/eudaldo/proyectos/liferay/trunk/com-liferay-journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java</td>
<td align="center" width="5%">6555</td>
<td width="*"><a href="http://pmd.sourceforge.net/pmd-5.2.3/pmd-java/rules/java/unusedcode.html#UnusedLocalVariable">Avoid unused local variables such as 'ownerType'.</a></td>
</tr>
<tr bgcolor="lightgrey"> 
<td align="center">3</td>
<td width="*%">/Users/eudaldo/proyectos/liferay/trunk/com-liferay-journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java</td>
<td align="center" width="5%">6556</td>
<td width="*"><a href="http://pmd.sourceforge.net/pmd-5.2.3/pmd-java/rules/java/unusedcode.html#UnusedLocalVariable">Avoid unused local variables such as 'plid'.</a></td>
</tr>
</table></body></html>

Regards.
Eudaldo

**Comment by mbowerman** [comment]
Thanks @jkappler and @ealonso! I will fix this and resend the pull.

**Pull request closed without merging**
